dhuoj/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
     path('article-list/', views.article_list, name='article_list'),
     path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
     path('article-create/', views.article_create, name='article_create'),
     path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
     path('article-update/<int:id>/', views.article_update, name='article_update'),
     path('article-search/<id>', views.article_search, name='article_search'),
     path('news-search/', views.news_search, name='news_search'),
]

dhuoj/dhuoj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('home.urls', namespace='home')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('problemset/', include('problemset.urls', namespace='problemset')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('problemlist/', include('problemlist.urls', namespace='problemlist')),
    path('team/', include('team.urls', namespace='team')),
    path('status/', include('judgestatus.urls', namespace='judgestatus')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dhuoj/problemlist/urls.py
from django.urls import path
from . import views

app_name = 'problemlist'

urlpatterns = [
    path('detail/<int:id>/', views.problemlist_detail, name='detail'),
    path('create/<int:id>/', views.problemlist_create, name='create'),
]

dhuoj/team/urls.py
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path('detail/<int:id>/', views.team_detail, name='detail'),
    path('', views.team_list, name='team_list'),
    path('team-create/', views.team_create, name='team_create'),
]

dhuoj/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
    path('<int:id>/', views.profile, name='profile'),
]

dhuoj/team/models.py
from django.db import models


class Team(models.Model):
    name = models.CharField(max_length=30)
    members = models.JSONField(null=True)
    # problemlists = models.JSONField(null=True)

    def __str__(self):
        return self.name

# Create your models here.

dhuoj/team/forms.py
from django import forms
from .models import Team

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = {'name', 'members'}

dhuoj/team/views.py
from problemlist.models import ProblemList
from .models import Team
from django.shortcuts import render, redirect
from userprofile.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import TeamForm


def team_detail(request, id):
    team = Team.objects.get(id=id)
    temp = ProblemList.objects.filter(team=team)
    members = team.members["members"]
    problemlists=[]
    for i in range(len(temp)):
        problemlist = temp[i]
        val = {
            "listID": int(problemlist.id),
            "listName": problemlist.listName,
            "problemNumber": len(problemlist.members["problems"])}
        problemlists.append(val)
    for i in range(len(members)):
        user = User.objects.filter(username=members[i])[0]
        members[i] = {
            "name": members[i],
            "id": user.id,
            "profile": Profile.objects.filter(user=user)[0]
        }
    context = {
        "teamID":id,
        "name": team.name,
        "members": members,
        "problemlists": problemlists
    }
    return render(request, 'team/detail.html', context)


def team_list(request):
    temp = Team.objects.all()
    teams = []
    for team in temp:
        val = {
            "id": team.id,
            "name": team.name,
            "user_number": len(team.members['members']),
            "problemlist_number": 0#len(team.problemlists['problemlists'])
        }
        teams.append(val)
    context = {"teams": teams}

    return render(request, 'team/team_list.html', context)

@login_required(login_url='/userprofile/login/')
def team_create(request):
    if request.method == 'POST':
        if request.user.username != 'admin':
            return HttpResponse("抱歉，你无权创建团队。")
        team_form = TeamForm(data=request.POST)
        if team_form.is_valid():
            new_team = team_form.save(commit=False)
            new_team.save()
            return redirect("team:team_list")
        else:
            return HttpResponse("input invalid !")
    else:
        team_form = TeamForm()
        context = {'team_form': team_form}
        return render(request, 'team/create.html', context)

dhuoj/templates/team/create.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>创建一个新团队</h1>
            <hr>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">团队名称</label>
                    <input type="text" class="form-control" id="name" name="name">
                </div>
                <div class="form-group">
                    <label for="body">成员</label>
                    <textarea type="text" class="form-control" id="members" name="members" rows="12">{"members":[]}</textarea>
                </div>
                <br>
                <div style="text-align:center">
                    <button type="submit" class="btn btn-lg btn-primary">提交</button>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

dhuoj/templates/team/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="row" style="background-color: rgb(239, 239, 239);">
    <div class="container-fluid col-md-10" style="background-color: white;">
        <br>
        <div class="row">
            <div class="col-3">
                <div class="card">
                    <img src="{% static 'images/dhuicon.png' %}" class="card-img"
                        style="max-width: 100%; border-radius: 100%;">
                    <div class="card-body">
                        <div class="card-title"><strong style="font-size:xx-large;">{{name}}</strong></div>
                        <div class="card-subtitle  mb-2 text-muted">
                            题单数: {{problemlists|length}}
                        </div>
                        <div class="card-subtitle  mb-2 text-muted">
                            成员数: {{members|length}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-9">
                <div class="row">
                    <div class="container-fluid">
                        <!-- 队名 -->
                        <div class="alert alert-primary pt-2 pb-2" role="alert">
                            <h3>{{ name }}</h3>
                        </div>

                        <div class="card col-12">
                            <div class="card-body">
                                <h5 class="card-title">题单
                                    {% if user.name == admin %}
                                    <a href="{% url 'problemlist:create' teamID %}" class="btn btn-primary">新建</a>
                                    {% endif %}
                                </h5>

                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th scope="col">题单名称</th>
                                            <th scope="col">题数</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for problemlist in problemlists %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'problemlist:detail' problemlist.listID %}"
                                                    style="text-decoration: none; color: black;">
                                                    {{problemlist.listName }}</a>
                                            </td>
                                            <td>
                                                <a href="{% url 'problemlist:detail' problemlist.listID %}"
                                                    style="text-decoration: none; color: black">
                                                    共{{problemlist.problemNumber }}题</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>


                            </div>
                        </div>

                        <div class="card col-12">
                            <div class="card-body">
                                <h5 class="card-title">成员
                                    <a href="" class="btn btn-primary">导入</a>

                                </h5>

                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th scope="col">用户名</th>
                                            <th scope="col">真实姓名</th>
                                            <th scope="col">专业班级</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for member in members %}
                                        <tr>
                                            <td>
                                                <a class="fw-bold"
                                                    style="color:rgb(117, 114, 114); text-decoration: none;"
                                                    href="{% url 'userprofile:profile' member.id %}">
                                                    {{ member.name }}
                                                </a>
                                            </td>
                                            <td>
                                                <a class="fw-bold"
                                                    style="color:rgb(117, 114, 114); text-decoration: none;"
                                                    href="{% url 'userprofile:profile' member.id %}">
                                                    {{ member.profile.realName }}
                                                </a>
                                            </td>
                                            <td>
                                                <a class="fw-bold"
                                                    style="color:rgb(117, 114, 114); text-decoration: none;"
                                                    href="{% url 'userprofile:profile' member.id %}">
                                                    {{ member.profile.major }}
                                                </a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>



                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>



{% endblock content %}

dhuoj/templates/team/team_list.html
{% extends "base.html" %}
{% load static %}


{% block content %}


<div class="row" style="background-color: rgb(239, 239, 239);">
    <div class="container-fluid col-md-8 col-sm-10" style="background-color: white;">
        <br>
        <h1>团队列表</h1>
        <hr>

        <a href="{% url 'team:team_create' %}" class="btn btn-primary">新建团队</a>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">团队名称</th>
                    <th scope="col">团队人数</th>
                    <th scope="col">题单数</th>
                </tr>
            </thead>
            <tbody>
                {% for team in teams %}
                <tr>
                    <td>
                        <a href="{% url 'team:detail' team.id %}"
                            style="text-decoration: none;color: black;font-size:medium;">
                            {{team.name}}
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'team:detail' team.id %}"
                            style="text-decoration: none;color: black;font-size: medium;">
                            {{team.user_number}}
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'team:detail' team.id %}"
                            style="text-decoration: none;color: black;font-size: medium;">
                            {{team.problemlist_number}}
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>



    </div>
</div>

{% endblock content %}