dhuoj/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
     path('article-list/', views.article_list, name='article_list'),
     path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
     path('article-create/', views.article_create, name='article_create'),
     path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
     path('article-update/<int:id>/', views.article_update, name='article_update'),
     path('article-search/<id>', views.article_search, name='article_search'),
     path('news-search/', views.news_search, name='news_search'),
]

dhuoj/dhuoj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('home.urls', namespace='home')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('problemset/', include('problemset.urls', namespace='problemset')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('problemlist/', include('problemlist.urls', namespace='problemlist')),
    path('team/', include('team.urls', namespace='team')),
    path('status/', include('judgestatus.urls', namespace='judgestatus')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dhuoj/home/urls.py
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

dhuoj/judgestatus/urls.py
from django.urls import path
from . import views
app_name = 'judgestatus'

urlpatterns = [
    path('', views.status_list_all, name='status_list_all'),
    path('<user_name>', views.status_list, name='status_list'),

]

dhuoj/problemset/urls.py
from django.urls import path
from . import views

app_name = 'problemset'

urlpatterns = [
    path('problem/<problem_id>', views.problem, name='problem'),
    path('', views.problemlist, name='problemlist'),
]

dhuoj/team/urls.py
from django.urls import path
from . import views

app_name = 'team'

urlpatterns = [
    path('detail/<int:id>/', views.team_detail, name='detail'),
    path('', views.team_list, name='team_list'),
    path('team-create/', views.team_create, name='team_create'),
]

dhuoj/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <title>DHU Online Jugde</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 新 Bootstrap5 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
    <!--  popper.min.js 用于弹窗、提示、下拉菜单 -->
    <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>
    <!-- 最新的 Bootstrap5 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.min.js"></script>


    <script>
        window.MathJax = {
            tex: {
                inlineMath: [["\\(", "\\)"]],
                displayMath: [["\\[", "\\]"]],
                processEscapes: true,
                processEnvironments: true
            },
            "HTML-CSS": {
                linebreaks: { automatic: true, width: "container" }
            },
            options: {
                ignoreHtmlClass: 'tex2jax_ignore',
                processHtmlClass: 'tex2jax_process',
                renderActions: {
                    find: [10, function (doc) {
                        for (const node of document.querySelectorAll('script[type^="math/tex"]')) {
                            const display = !!node.type.match(/; *mode=display/);
                            const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
                            const text = document.createTextNode('');
                            const sibling = node.previousElementSibling;
                            node.parentNode.replaceChild(text, node);
                            math.start = { node: text, delim: '', n: 0 };
                            math.end = { node: text, delim: '', n: 0 };
                            doc.math.push(math);
                            if (sibling && sibling.matches('.MathJax_Preview')) {
                                sibling.parentNode.removeChild(sibling);
                            }
                        }
                    }, '']
                }
            }
        };
    </script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
    <link rel="stylesheet" href="{% static 'md_css/borland.css' %}">


    <script src="{% static 'jquery/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>

</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
</body>

</html>

dhuoj/templates/footer.html
<div class="container-fluid">
    <footer class="py-3 my-4 ">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home |</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About |</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Administrator
                    Entrance</a>
            </li>
        </ul>
        <p class="text-center text-muted">B431 Comprehensive Lab Building, Songjiang Campus, Donghua University</p>
        <p class="text-center text-muted">2999 North Renmin Road, Shanghai, 201620</p>
        <p class="text-center text-muted">Copyright© 2022 Donghua University ACM Lab. All Right Reserved.</p>
    </footer>
</div>

dhuoj/templates/header.html
{% load static %}

<div class="container-fluid pt-2 pb-2 bg-primary text-white">
    <div class="row">
        <div class="col-md-8">
            <table>
                <tr>
                    <td width="150"><img src="{% static 'images/logo.png' %}" height="90px" /></td>
                    <td>
                        <h1> DHU Online Judge</h1>
                        <p>Developed by ACM Training Team of Donghua University</p>
                    </td>
                </tr>
            </table>
        </div>
        <div class="col-md-4">

        </div>
    </div>

</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:home' %}">DHUOJ</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">首页</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        题目集
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'problemset:problemlist' %}">题目列表</a></li>
                        <li><a class="dropdown-item" href="#">提交</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <form class="d-flex" role="search" aria-label="go_to_problem">
                                <input class="form-control me-1" type="search" placeholder="Prob.ID"
                                    aria-label="Search">
                                <button class="btn btn-outline-success" type="submit">GO</button>
                            </form>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'judgestatus:status_list_all' %}">状态</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#">比赛</a>
                </li> -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:article_list' %}">博客</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'team:team_list' %}">团队</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:news_search' %}">新闻</a>
                </li>

            </ul>
            <!-- <form class="d-flex" role="search" aria-label="search_info">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form> -->
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'userprofile:profile' user.id %}">个人信息</a></li>
                        <li><a class="dropdown-item" href=' {% url "userprofile:logout" %}' style="color:#F00">退出登录</a>
                        </li>
                    </ul>
                </li>
                <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                </li>
                <!-- if 语句在这里结束 -->
                {% endif %}
            </ul>
        </div>
    </div>
</nav>