dhuoj/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
     path('article-list/', views.article_list, name='article_list'),
     path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
     path('article-create/', views.article_create, name='article_create'),
     path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
     path('article-update/<int:id>/', views.article_update, name='article_update'),
     path('article-search/<id>', views.article_search, name='article_search'),
     path('news-search/', views.news_search, name='news_search'),
]

dhuoj/dhuoj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('home.urls', namespace='home')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('problemset/', include('problemset.urls', namespace='problemset')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('problemlist/', include('problemlist.urls', namespace='problemlist')),
    path('team/', include('team.urls', namespace='team')),
    path('status/', include('judgestatus.urls', namespace='judgestatus')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dhuoj/home/urls.py
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

dhuoj/problemset/urls.py
from django.urls import path
from . import views

app_name = 'problemset'

urlpatterns = [
    path('problem/<problem_id>', views.problem, name='problem'),
    path('', views.problemlist, name='problemlist'),
]

dhuoj/home/views.py
from django.shortcuts import render
from blog.models import ArticlePost, ArticleColumn
from problemset.models import Problem


def home(request):
    new_article = ArticlePost.objects.all()[:3]
    new_problem = Problem.objects.all()[:3]
    news = ArticlePost.objects.filter(column__title="新闻")[:3]
    print(news)
    context = {
        "new_article": new_article,
        "new_problem": new_problem,
        "news": news
    }
    return render(request, 'home/index.html', context)

dhuoj/templates/home/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<style type="text/css">
    a {
        text-decoration: none
    }
</style>
<div class="row" style="background-color: rgb(239, 239, 239);">
    <div class="container-fluid col-md-10" style="background-color: white;">
        <div class="row">
            <div class="col-md-8">
                <div class="card" style="width:fit-content; height:fit-content;">
                    <img src="{% static 'images/wife.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="card-text">Developed by ACM Training Team of Donghua University</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <ul class="list-group">
                    <div class="alert alert-primary pt-2 pb-2" role="alert">
                        新闻
                    </div>
                    {% for article in news %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">
                                <a href="{% url 'blog:article_detail' article.id %}">{{article.title}}</a>
                            </div>
                            <span class="badge bg-primary rounded-pill">{{article.created|date:"Y/m/d"}}</span>
                            {{ article.body|slice:'80' }}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
</div>

<div class="row" style="background-color: rgb(239, 239, 239);">
    <div class="container-fluid col-md-10" style="background-color: white;">
        <br>
        <div class="row">
            <div class="col-md-6">
                <ul class="list-group">
                    <div class="alert alert-primary pt-2 pb-2" role="alert">
                        最新文章
                    </div>
                    {% for article in new_article %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">
                                <a href="{% url 'blog:article_detail' article.id %}">{{article.title}}</a>
                            </div>
                            <span class="badge bg-primary rounded-pill">{{article.created|date:"Y/m/d"}}</span>
                            {{ article.body|slice:'80' }}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="list-group">
                    <div class="alert alert-primary pt-2 pb-2" role="alert">
                        最新题目
                    </div>
                    {% for problem in new_problem %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">
                                <a href="{% url 'problemset:problem' problem.problemID %}">{{problem.title}}</a>
                            </div>
                            <span class="badge bg-primary rounded-pill">{{problem.problemID}}</span>
                            {{ problem.problem_description|slice:'80' }}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
</div>

{% endblock content %}