dhuoj/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
     path('article-list/', views.article_list, name='article_list'),
     path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
     path('article-create/', views.article_create, name='article_create'),
     path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
     path('article-update/<int:id>/', views.article_update, name='article_update'),
     path('article-search/<id>', views.article_search, name='article_search'),
     path('news-search/', views.news_search, name='news_search'),
]

dhuoj/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 一级评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
    # 二级评论
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment-reply'),
]

dhuoj/dhuoj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('home.urls', namespace='home')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('problemset/', include('problemset.urls', namespace='problemset')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('problemlist/', include('problemlist.urls', namespace='problemlist')),
    path('team/', include('team.urls', namespace='team')),
    path('status/', include('judgestatus.urls', namespace='judgestatus')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dhuoj/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
    path('<int:id>/', views.profile, name='profile'),
]

dhuoj/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class ArticleColumn(models.Model):
    """
    栏目的 Model
    """
    # 标签
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)
    # 文章栏目的 “一对多” 外键
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('blog:article_detail', args=[self.id])

dhuoj/blog/forms.py
from django import forms
from .models import ArticlePost


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body')

dhuoj/blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ArticlePostForm
from .models import ArticlePost
from django.contrib.auth.models import User
import markdown
from .models import ArticleColumn
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm


def article_list(request):
    search = request.GET.get('search')
    if search:
        articles = ArticlePost.objects.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search) |
            Q(column__title__icontains=search)
        )
    else:
        search = ''
        articles = ArticlePost.objects.all()
    context = {'articles': articles, 'search': search}
    return render(request, 'blog/list.html', context)

def article_search(request, id):
    articles = ArticlePost.objects.filter(
        Q(title__icontains=id) |
        Q(body__icontains=id) |
        Q(column__title__icontains=id)
    )
    context = { 'articles': articles, 'search': id }
    return render(request, 'blog/list.html', context)

def news_search(request):
    search = '新闻'
    articles = ArticlePost.objects.filter(
        Q(title__icontains=search) |
        Q(body__icontains=search) |
        Q(column__title__icontains=search)
    )
    context = {'articles': articles, 'search': search}
    return render(request, 'blog/list.html', context)

def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    # 取出文章评论
    comments = Comment.objects.filter(article=id)
    article.total_views += 1
    article.save(update_fields=['total_views'])
    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         'markdown.extensions.extra',
                                         'markdown.extensions.codehilite',
                                         'pymdownx.arithmatex',
                                     ]
                                     )
    comment_form = CommentForm()
    context = {'article': article,
               'comments': comments,
               'comment_form': comment_form,
               }
    return render(request, 'blog/detail.html', context)

# 写文章的视图


@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(
                    id=request.POST['column'])
            new_article.save()
            return redirect("blog:article_list")
        else:
            return HttpResponse("input invalid !")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = {'article_post_form': article_post_form, 'columns': columns}
        return render(request, 'blog/create.html', context)


@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        if request.user != article.author:
            return HttpResponse("抱歉，你无权删除这篇文章。")
        article.delete()
        return redirect("blog:article_list")
    else:
        return HttpResponse("仅接受POST请求。")

# 更新文章的视图


@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(
                    id=request.POST['column'])
            else:
                article.column = None
            article.save()
            # 完成后返回到修改后的文章中。需传入文章 id
            return redirect("blog:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        context = {'article': article,
                   'article_post_form': article_post_form, 'columns': columns, }
        # 将响应返回到模板
        return render(request, 'blog/update.html', context)

dhuoj/templates/blog/create.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>发布一篇新文章</h1>
            <hr>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章标签 -->
                <div class="form-group">
                    <label for="column">标签</label>
                    <select class="form-control" id="column" name="column">
                        <option value="none">请选择标签..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">正文</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <br>
                <div style="text-align:center">
                    <button type="submit" class="btn btn-lg btn-primary">提交</button>
                </div>
            </form>
        </div>
    </div>
</div>





{% endblock content %}

dhuoj/templates/blog/detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<div class="row">

    <div class="container-fluid col-md-8 col-sm-10">
        <div class="row">
            <!-- 标题 -->
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
            <!-- 作者 -->
            <div class="col-12 alert alert-success">作者: {{ article.author }}
                {% if user == article.author %}
                <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                <a href="{% url 'blog:article_update' article.id %}">编辑文章</a>
                {% endif %}
                <div>
                    浏览：{{ article.total_views }}
                </div>
                <form style="display:none;" id="safe_delete" action="{% url 'blog:article_safe_delete' article.id %}"
                    method="POST">
                    {% csrf_token %}
                    <button type="submit">发送</button>
                </form>
            </div>
            <!-- 正文 -->
            <div class="col-12">
                <p>{{ article.body|safe }}</p>
            </div>
            <!-- 发送评论 -->
            <hr>
            {% if user.is_authenticated %}
            <div>
                <form action="{% url 'comment:post_comment' article.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>
                                我也要发言：
                            </strong>
                        </label>
                        <div>
                            {{ comment_form.media }}
                            {{ comment_form.body }}
                        </div>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary ">发送</button>
                </form>
            </div>
            <br>
            {% else %}
            <br>
            <h5 class="row justify-content-center">
                请<a href="{% url 'userprofile:login' %}">登录</a>后回复
            </h5>
            <br>
            {% endif %}
            <!-- 显示评论 -->
            <p>共有{{ comments.count }}条评论</p>
            <div>
                {% for comment in comments %}

                <div class="card">
                    <div class="card-header">
                        <strong style="color: rgba(166, 164, 168, 0.76)">
                            <a href="{% url 'userprofile:profile' comment.user.id %}" style="text-decoration: none;">
                                {{comment.user}}
                            </a>
                            {{ comment.created|date:"Y-m-d H:i:s" }}
                        </strong>
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <pre style="font-family: inherit; font-size: 1em;">
                                {{ comment.body|safe }}
                            </pre>
                        </blockquote>
                    </div>
                </div>


                {% endfor %}
            </div>
            <!-- {% load mptt_tags %}
            <h4>共有{{ comments.count }}条评论</h4>
            <div class="row">
                {% recursetree comments %}
                {% with comment=node %}
                <div class="{% if comment.reply_to %}
                                    offset-1 col-11
                                    {% else %}
                                    col-12
                                    {% endif %}">
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong>

                        {% if comment.reply_to %}
                        <i class="far fa-arrow-alt-circle-right" style="color: cornflowerblue;"></i>
                        <strong style="color: pink">
                            {{ comment.reply_to }}
                        </strong>
                        {% endif %}

                    </p>
                    <div>{{ comment.body|safe }}</div>

                    <div>
                        <span style="color: gray">
                            {{ comment.created|date:"Y-m-d H:i" }}
                        </span>

                        {% if user.is_authenticated %}
                        <button type="button" class="btn btn-light btn-sm text-muted"
                            onclick="load_modal({{ article.id }}, {{ comment.id }})">
                            回复
                        </button>
                        {% else %}
                        <a class="btn btn-light btn-sm text-muted" href="{% url 'userprofile:login' %}">
                            回复
                        </a>
                        {% endif %}
                    </div>

                    <div class="modal fade" id="comment_{{ comment.id }}" tabindex="-1" role="dialog"
                        aria-labelledby="CommentModalCenter" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                            <div class="modal-content" style="height: 480px">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                                </div>
                                <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                            </div>

                        </div>
                    </div>

                    {% if not comment.is_leaf_node %}
                    <div class="children">
                        {{ children }}
                    </div>
                    {% endif %}
                </div>


                {% endwith %}
                {% endrecursetree %}
            </div>
        </div>
    </div>
</div>


{% block script %} -->

            <script>
                function confirm_safe_delete() {
                    layer.open({
                        title: "确认删除",
                        content: "确认删除这篇文章吗？",
                        yes: function (index, layero) {
                            $('form#safe_delete button').click();
                            layer.close(index);
                        },
                    })
                }
            </script>

            <!-- 新增代码，唤醒二级回复的 modal -->
            <script>
                // 加载 modal
                function load_modal(article_id, comment_id) {
                    let modal_body = '#modal_body_' + comment_id;
                    let modal_id = '#comment_' + comment_id;

                    // 加载编辑器
                    if ($(modal_body).children().length === 0) {
                        let content = '<iframe src="/comment/post-comment/' +
                            article_id +
                            '/' +
                            comment_id +
                            '"' +
                            ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                            comment_id +
                            '"></iframe>';
                        $(modal_body).append(content);
                    };

                    $(modal_id).modal('show');
                }
            </script>
            {% endblock script %}

            {% endblock content %}

dhuoj/templates/blog/list.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<style type="text/css">
    a {
        text-decoration: none
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-3 text-white bg-primary border-primary">
                    <h4 class="my-0 fw-normal">Blog</h4>
                </div>
                <div class="card-body">
                    <ul class="nav nav-pills flex-column mb-auto">
                        <li>
                            <a href="{% url 'blog:article_create' %}" class="nav-link bg-primary text-white">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                </svg>
                                发布新文章
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link link-dark">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                    <use xlink:href="#speedometer2"></use>
                                </svg>
                                All
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link link-dark">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                    <use xlink:href="#speedometer2"></use>
                                </svg>
                                Self
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link link-dark">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                    <use xlink:href="#table"></use>
                                </svg>
                                Top rated
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <form class="form-inline">
                <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索文章..." required>
            </form>
            {% if search %}
            {% if articles %}
            <p><span style="color: red">"{{ search }}"</span>的搜索结果如下：</p>
            <ul class="list-group">
                {% for article in articles %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <!-- 标签 -->
                    {% if article.column %}
                    <button type="button" class="btn btn-sm mb-2" style="color: white;background-color: black">
                        {{ article.column }}
                    </button>
                    {% endif %}

                    <div class="ms-2 me-auto">
                        <div class="fw-bold">
                            <a href="{% url 'blog:article_detail' article.id %}">
                                {{ article.title}}
                            </a>
                            <!-- 显示浏览量 -->
                            <span>
                                <small class="col align-self-end" style="color: gray;">
                                    浏览: {{ article.total_views }}
                                </small>
                            </span>
                        </div>
                        {{ article.body|slice:'150' }}
                    </div>
                    <span class="badge bg-primary rounded-pill">{{article.created|date:"Y/m/d"}}</span>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>暂无与<span style="color: red">"{{ search }}"</span>有关的文章。</p>
            {% endif %}
            {% else %}
            <ul class="list-group">
                {% for article in articles %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <!-- 标签 -->
                    {% if article.column %}
                    <button type="button" class="btn btn-sm mb-2" style="color: white;background-color: black">
                        {{ article.column }}
                    </button>
                    {% endif %}

                    <div class="ms-2 me-auto">
                        <div class="fw-bold">
                            <a href="{% url 'blog:article_detail' article.id %}">
                                {{ article.title}}
                            </a>
                            <!-- 显示浏览量 -->
                            <span>
                                <small class="col align-self-end" style="color: gray;">
                                    浏览: {{ article.total_views }}
                                </small>
                            </span>
                        </div>
                        {{ article.body|slice:'150' }}
                    </div>
                    <span class="badge bg-primary rounded-pill">{{article.created|date:"Y/m/d"}}</span>
                </li>
                {% endfor %}
            </ul>
            {% endif %}

        </div>
    </div>

</div>
{% endblock content %}

dhuoj/templates/blog/search.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<style type="text/css">
    a {
        text-decoration: none
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-3 text-white bg-primary border-primary">
                    <h4 class="my-0 fw-normal">Blog</h4>
                </div>
                <div class="card-body">
                    <ul class="nav nav-pills flex-column mb-auto">
                        <li>
                            <a href="{% url 'blog:article_create' %}" class="nav-link bg-primary text-white">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                </svg>
                                发布新文章
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link link-dark">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                    <use xlink:href="#speedometer2"></use>
                                </svg>
                                All
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link link-dark">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                    <use xlink:href="#speedometer2"></use>
                                </svg>
                                Self
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link link-dark">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                    <use xlink:href="#table"></use>
                                </svg>
                                Top rated
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <div class="col-md-9">
            <form class="form-inline">
                <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索文章..." required>
            </form>
            {% if articles %}
            <p><span style="color: red">"{{ search }}"</span>的搜索结果如下：</p>
            <ul class="list-group">
                {% for article in articles %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <!-- 标签 -->
                    {% if article.column %}
                    <button type="button" class="btn btn-sm mb-2" style="color: white;background-color: black">
                        {{ article.column }}
                    </button>
                    {% endif %}

                    <div class="ms-2 me-auto">
                        <div class="fw-bold">
                            <a href="{% url 'blog:article_detail' article.id %}">
                                {{ article.title}}
                            </a>
                            <!-- 显示浏览量 -->
                            <span>
                                <small class="col align-self-end" style="color: gray;">
                                    浏览: {{ article.total_views }}
                                </small>
                            </span>
                        </div>
                        {{ article.body|slice:'150' }}
                    </div>
                    <span class="badge bg-primary rounded-pill">{{article.created|date:"Y/m/d"}}</span>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>暂无与<span style="color: red">"{{ search }}"</span>有关的文章。</p>
            {% endif %}

        </div>
    </div>

</div>
{% endblock content %}

dhuoj/templates/blog/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>更新文章</h1>
            <hr>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <label for="title">标题</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <!-- 文章标签 -->
                <div class="form-group">
                    <label for="column">标签</label>
                    <select class="form-control" id="column" name="column">
                        <option value="none">请选择标签..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                {% if column.id == article.column.id %}
                                    selected
                                {% endif %}
                            >
                                {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">正文</label>
                    <textarea type="text" class="form-control" id="body" name="body"
                        rows="12">{{ article.body }}</textarea>
                </div>
                <br>
                <div style="text-align:center">
                    <button type="submit" class="btn btn-lg btn-primary">提交</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}